// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oorbusgezrrtupaizhrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vcmJ1c2dlenJydHVwYWl6aHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5Njk0NzYsImV4cCI6MjA1NzU0NTQ3Nn0.4SNvj5pk8xvabSA4FyMekXQ-t_Rmf3KlFyoihB2mJvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);